- hosts: ["kafka"]
  pre_tasks:
    - name: check kafka installed
      stat:
        path: /opt/kafka
      register: kafka_installed

  tasks:
  - name: "kafka start"
    systemd:
      name: kafka
      state: stopped
    become: true
    when: kafka_installed.stat.exists
