- hosts: ["namenode2"]
  pre_tasks:
    - name: check hadoop installed
      stat:
        path: /opt/hadoop
      register: hadoop_installed

  tasks:
  - name: "namenode2 start"
    shell: |
      /opt/hadoop/bin/hdfs namenode -bootstrapStandby
      /opt/hadoop/bin/hdfs --daemon start namenode
      
    when: hadoop_installed.stat.exists
