- hosts: ["namenode","kafka","zookeeper"]
  tasks:
  - name: "copy jmx file"
    template:
      src: 'test.jmx'
      dest: '/tmp'
  - name: "start jmeter"
    shell: jmeter -n -t /tmp/test.jmx -l /tmp/result
